name: Update iptv

on:
  schedule:
    # 
    - cron: '0 0 * * *'
  workflow_dispatch:

# env:

permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted
    #container: 
      #image: python:3.11-slim

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    #- name: Set up Python
      #uses: actions/setup-python@v5
      #with:
        #python-version: '3.11' # 推荐使用 3.11 以获取更佳的 asyncio 性能

    - name: Increase open files limit
      run: |
        ulimit -n 65536
        echo "Default open files limit increased for high-concurrency connections."

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp uvloop

    - name: Run M3U Check Script
      run: python main.py

    - name: Commit and Push M3U file
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add itvlist.m3u
        # 如果文件没有变化，则不报错退出
        git commit -m "Update iptv list[skip ci]" || exit 0
        git push
